import type { Question } from "./types";

export const TOTAL_PICKS = 40;

export const QUESTIONS: Question[] = [
  {
    id: "q1",
    number: 1,
    pick: 5,
    scene: "O que te acende",
    title: "O que te deixa mais motivado no trabalho?",
    hint: "Escolha exatamente 5 situações. Vá pelo que realmente te move — não pelo que “parece certo”.",
    options: [
      { id: "1.1", label: "Trabalhar sozinho", quadrant: "SE" },
      { id: "1.2", label: "Expressar minhas ideias", quadrant: "ID" },
      { id: "1.3", label: "Estar no controle da situação", quadrant: "IE" },
      { id: "1.4", label: "Provocar mudanças", quadrant: "SD" },
      { id: "1.5", label: "Ouvir e falar", quadrant: "ID" },
      { id: "1.6", label: "Criar ou usar recursos visuais", quadrant: "SD" },
      { id: "1.7", label: "Prestar atenção aos detalhes", quadrant: "IE" },
      { id: "1.8", label: "Aspectos técnicos", quadrant: "SE" },
      { id: "1.9", label: "Trabalhar com pessoas", quadrant: "ID" },
      { id: "1.10", label: "Usar números e estatísticas", quadrant: "SE" },
      { id: "1.11", label: "Oportunidades para fazer experiências", quadrant: "SD" },
      { id: "1.12", label: "Planejar", quadrant: "IE" },
      { id: "1.13", label: "Trabalhar com comunicação", quadrant: "ID" },
      { id: "1.14", label: "Fazer algo funcionar", quadrant: "SE" },
      { id: "1.15", label: "Arriscar-se", quadrant: "SD" },
      { id: "1.16", label: "Analisar dados", quadrant: "SE" },
      { id: "1.17", label: "Lidar com o futuro", quadrant: "SD" },
      { id: "1.18", label: "Produzir e organizar", quadrant: "IE" },
      { id: "1.19", label: "Fazer parte de uma equipe", quadrant: "ID" },
      { id: "1.20", label: "Fazer as coisas sempre no prazo previsto", quadrant: "IE" },
    ],
  },
  {
    id: "q2",
    number: 2,
    pick: 5,
    scene: "Como você aprende",
    title: "Quando aprende, você gosta de…",
    hint: "Escolha exatamente 5 alternativas.",
    options: [
      { id: "2.1", label: "Avaliar e testar teorias", quadrant: "IE" },
      { id: "2.2", label: "Obter e quantificar fatos", quadrant: "SE" },
      { id: "2.3", label: "Ouvir e compartilhar ideias", quadrant: "ID" },
      { id: "2.4", label: "Usar minha imaginação", quadrant: "SD" },
      { id: "2.5", label: "Aplicar análise e lógica", quadrant: "SE" },
      { id: "2.6", label: "Ambiente bem informal", quadrant: "SD" },
      { id: "2.7", label: "Verificar meu entendimento", quadrant: "IE" },
      { id: "2.8", label: "Fazer experiências práticas", quadrant: "ID" },
      { id: "2.9", label: "Pensar sobre as ideias", quadrant: "SE" },
      { id: "2.10", label: "Confiar nas intuições", quadrant: "ID" },
      { id: "2.11", label: "Receber informações passo a passo", quadrant: "IE" },
      { id: "2.12", label: "Tomar iniciativas", quadrant: "SD" },
      { id: "2.13", label: "Elaborar teorias", quadrant: "IE" },
      { id: "2.14", label: "Envolvimento emocional", quadrant: "ID" },
      { id: "2.15", label: "Trabalhar em grupo", quadrant: "ID" },
      { id: "2.16", label: "Orientações claras", quadrant: "IE" },
      { id: "2.17", label: "Fazer descobertas", quadrant: "SD" },
      { id: "2.18", label: "Criticar", quadrant: "SE" },
      { id: "2.19", label: "Perceber logo o quadro geral (o objetivo final)", quadrant: "SD" },
      { id: "2.20", label: "Adquirir habilidades pela prática", quadrant: "IE" },
    ],
  },
  {
    id: "q3",
    number: 3,
    pick: 5,
    scene: "Seu jeito de absorver",
    title: "Você prefere aprender através de…",
    hint: "Escolha exatamente 5 alternativas.",
    options: [
      { id: "3.1", label: "Materiais visuais", quadrant: "SD" },
      { id: "3.2", label: "Demonstrações", quadrant: "ID" },
      { id: "3.3", label: "Debates estruturados pelo instrutor", quadrant: "IE" },
      { id: "3.4", label: "Palestras formais", quadrant: "SE" },
      { id: "3.5", label: "Experiências", quadrant: "SD" },
      { id: "3.6", label: "Histórias e música", quadrant: "ID" },
      { id: "3.7", label: "Exercícios que usam a intuição", quadrant: "ID" },
      { id: "3.8", label: "Debate em grupo", quadrant: "SD" },
      { id: "3.9", label: "Exercícios de análise", quadrant: "SE" },
      { id: "3.10", label: "Atividades sequenciais bem planejadas", quadrant: "IE" },
      { id: "3.11", label: "Analisar números, dados e fatos", quadrant: "SE" },
      { id: "3.12", label: "Exemplos com metáforas", quadrant: "SD" },
      { id: "3.13", label: "Atividades passo a passo de reforço", quadrant: "IE" },
      { id: "3.14", label: "Leitura de livros-texto", quadrant: "IE" },
      { id: "3.15", label: "Discussões de casos voltadas para as pessoas", quadrant: "ID" },
      { id: "3.16", label: "Discussões de casos voltadas para números e fatos", quadrant: "SE" },
      { id: "3.17", label: "Métodos tradicionais comprovados", quadrant: "IE" },
      { id: "3.18", label: "Agenda bem flexível", quadrant: "SD" },
      { id: "3.19", label: "Agenda estruturada com antecedência", quadrant: "SE" },
      { id: "3.20", label: "Trabalhos bem estruturados", quadrant: "ID" },
    ],
  },
  {
    id: "q4",
    number: 4,
    pick: 1,
    scene: "A pergunta que você faz",
    title: "Qual o tipo de pergunta que você mais gosta de fazer?",
    hint: "Escolha somente 1.",
    options: [
      { id: "4.1", label: "O quê?", quadrant: "SE" },
      { id: "4.2", label: "Como?", quadrant: "IE" },
      { id: "4.3", label: "Por quê?", quadrant: "SD" },
      { id: "4.4", label: "Quem?", quadrant: "ID" },
    ],
  },
  {
    id: "q5",
    number: 5,
    pick: 4,
    scene: "O que você ama fazer",
    title: "O que você mais gosta de fazer?",
    hint: "Escolha exatamente 4.",
    options: [
      { id: "5.1", label: "Descobrir", quadrant: "SD" },
      { id: "5.2", label: "Quantificar", quadrant: "SE" },
      { id: "5.3", label: "Envolver", quadrant: "ID" },
      { id: "5.4", label: "Organizar", quadrant: "IE" },
      { id: "5.5", label: "Conceituar", quadrant: "SD" },
      { id: "5.6", label: "Analisar", quadrant: "SE" },
      { id: "5.7", label: "Sentir", quadrant: "ID" },
      { id: "5.8", label: "Praticar", quadrant: "IE" },
      { id: "5.9", label: "Teorizar", quadrant: "SE" },
      { id: "5.10", label: "Sintetizar", quadrant: "SD" },
      { id: "5.11", label: "Avaliar", quadrant: "IE" },
      { id: "5.12", label: "Interiorizar", quadrant: "ID" },
      { id: "5.13", label: "Processar", quadrant: "SE" },
      { id: "5.14", label: "Ordenar", quadrant: "IE" },
      { id: "5.15", label: "Explorar", quadrant: "SD" },
      { id: "5.16", label: "Compartilhar", quadrant: "ID" },
    ],
  },
  {
    id: "q6",
    number: 6,
    pick: 5,
    scene: "Você vai comprar um carro",
    title: "Ao comprar um carro, o que melhor define você?",
    hint: "Escolha exatamente 5 frases. Pense no seu comportamento real — não no “ideal”.",
    options: [
      { id: "6.1", label: "Compro com base na recomendação de amigos", quadrant: "ID" },
      { id: "6.2", label: "Me preocupo com o consumo de combustível", quadrant: "SE" },
      { id: "6.3", label: "Me preocupo com as formas, a cor e a tecnologia", quadrant: "SD" },
      { id: "6.4", label: "Verifico equipamento de segurança e durabilidade", quadrant: "IE" },
      { id: "6.5", label: "Dou importância à “sensação” de conforto do veículo", quadrant: "ID" },
      { id: "6.6", label: "Faço comparações com outros veículos", quadrant: "SE" },
      { id: "6.7", label: "Verifico o tamanho do porta-malas", quadrant: "IE" },
      { id: "6.8", label: "Verifico se encaixa no meu sonho de vida", quadrant: "SD" },
      { id: "6.9", label: "Pesquisa e planejo antecipadamente como vou utilizá-lo", quadrant: "IE" },
      { id: "6.10", label: "Me preocupo com o custo e o valor de troca", quadrant: "SE" },
      { id: "6.11", label: "Quero “amar” o carro", quadrant: "ID" },
      { id: "6.12", label: "Prefiro carros lançados recentemente, novidades", quadrant: "SD" },
      { id: "6.13", label: "Me preocupo com os requisitos técnicos", quadrant: "IE" },
      { id: "6.14", label: "Verifico a facilidade de manutenção", quadrant: "SE" },
      { id: "6.15", label: "Gosto de experimentar um novo modelo ou fabricante", quadrant: "SD" },
      { id: "6.16", label: "Me preocupo com o nome do fabricante", quadrant: "ID" },
      { id: "6.17", label: "Dou importância à opinião das pessoas", quadrant: "SD" },
      { id: "6.18", label: "Quero ver dados e estatísticas sobre o desempenho", quadrant: "SE" },
      { id: "6.19", label: "Me preocupo com a qualidade do atendimento do revendedor", quadrant: "ID" },
      { id: "6.20", label: "Analiso como o carro vai ser útil no meu dia a dia", quadrant: "IE" },
    ],
  },
  {
    id: "q7",
    number: 7,
    pick: 1,
    scene: "Em uma frase",
    title: "Como você define o seu comportamento?",
    hint: "Escolha somente 1.",
    options: [
      { id: "7.1", label: "Gosto de organizar", quadrant: "IE" },
      { id: "7.2", label: "Gosto de compartilhar", quadrant: "ID" },
      { id: "7.3", label: "Gosto de analisar", quadrant: "SE" },
      { id: "7.4", label: "Gosto de descobrir", quadrant: "SD" },
    ],
  },
  {
    id: "q8",
    number: 8,
    pick: 4,
    scene: "Palavras do seu estilo",
    title: "Quais palavras definem o seu estilo?",
    hint: "Escolha exatamente 4.",
    options: [
      { id: "8.1", label: "Organizado", quadrant: "IE" },
      { id: "8.2", label: "Analítico", quadrant: "SE" },
      { id: "8.3", label: "Emocional", quadrant: "ID" },
      { id: "8.4", label: "Experimental", quadrant: "SD" },
      { id: "8.5", label: "Lógico", quadrant: "SE" },
      { id: "8.6", label: "Conceitual", quadrant: "SD" },
      { id: "8.7", label: "Perceptivo", quadrant: "ID" },
      { id: "8.8", label: "Sequencial", quadrant: "IE" },
      { id: "8.9", label: "Teórico", quadrant: "SE" },
      { id: "8.10", label: "Explorador", quadrant: "SD" },
      { id: "8.11", label: "Avaliador", quadrant: "IE" },
      { id: "8.12", label: "Cinestésico", quadrant: "ID" },
      { id: "8.13", label: "Sentimental", quadrant: "ID" },
      { id: "8.14", label: "Preparado", quadrant: "IE" },
      { id: "8.15", label: "Quantitativo", quadrant: "SE" },
      { id: "8.16", label: "Sintético", quadrant: "SD" },
    ],
  },
  {
    id: "q9",
    number: 9,
    pick: 5,
    scene: "O que falam de você",
    title: "Quais frases depreciativas você mais ouve a seu respeito?",
    hint: "Escolha exatamente 5. Pode doer um pouco — e é por isso que funciona.",
    options: [
      { id: "9.1", label: "Viciado em números", quadrant: "SE" },
      { id: "9.2", label: "Coração mole", quadrant: "ID" },
      { id: "9.3", label: "Exigente, esforçado", quadrant: "IE" },
      { id: "9.4", label: "Vive no mundo da lua", quadrant: "SD" },
      { id: "9.5", label: "Tem sede de poder", quadrant: "SE" },
      { id: "9.6", label: "Fala demais", quadrant: "ID" },
      { id: "9.7", label: "Não decide sozinho", quadrant: "IE" },
      { id: "9.8", label: "Não sabe se concentrar", quadrant: "SD" },
      { id: "9.9", label: "Frio, insensível", quadrant: "SE" },
      { id: "9.10", label: "Fácil de convencer", quadrant: "ID" },
      { id: "9.11", label: "Sem imaginação", quadrant: "IE" },
      { id: "9.12", label: "Maluco", quadrant: "SD" },
      { id: "9.13", label: "Calculista", quadrant: "SE" },
      { id: "9.14", label: "Ingênuo", quadrant: "ID" },
      { id: "9.15", label: "Bitolado", quadrant: "IE" },
      { id: "9.16", label: "Inconsequente", quadrant: "SD" },
      { id: "9.17", label: "Não se mistura", quadrant: "SE" },
      { id: "9.18", label: "Ultra-sensível", quadrant: "ID" },
      { id: "9.19", label: "Quadrado", quadrant: "IE" },
      { id: "9.20", label: "Sem disciplina", quadrant: "SD" },
    ],
  },
  {
    id: "q10",
    number: 10,
    pick: 1,
    scene: "Na hora do problema",
    title: "Quando tem que resolver um problema, você geralmente…",
    hint: "Escolha somente 1.",
    options: [
      {
        id: "10.1",
        label: "Visualizo os fatos, tratando-os de forma intuitiva e holística",
        quadrant: "SD",
      },
      {
        id: "10.2",
        label: "Organizo os fatos, tratando os detalhes de forma realista e cronológica",
        quadrant: "IE",
      },
      {
        id: "10.3",
        label: "Sinto os fatos, tratando-os de forma expressiva e interpessoal",
        quadrant: "ID",
      },
      {
        id: "10.4",
        label: "Analiso os fatos, tratando-os de forma lógica e racional",
        quadrant: "SE",
      },
    ],
  },
  {
    id: "q11",
    number: 11,
    pick: 1,
    scene: "A lente que você usa",
    title: "Quando tem que resolver um problema, você procura…",
    hint: "Escolha somente 1.",
    options: [
      { id: "11.1", label: "Uma visão interpessoal, emocional, “humana”", quadrant: "ID" },
      { id: "11.2", label: "Uma visão organizada, detalhada, “cronológica”", quadrant: "IE" },
      { id: "11.3", label: "Uma visão analítica, lógica, racional, “de resultados”", quadrant: "SE" },
      { id: "11.4", label: "Uma visão intuitiva, conceitual, visual, de “contexto geral”", quadrant: "SD" },
    ],
  },
  {
    id: "q12",
    number: 12,
    pick: 3,
    scene: "O que sai da sua boca",
    title: "Quais frases mais se aproximam do que você diz?",
    hint: "Escolha exatamente 3.",
    options: [
      { id: "12.1", label: "Sempre fazemos desta forma…", quadrant: "IE" },
      { id: "12.2", label: "Vamos ao ponto-chave do problema…", quadrant: "SE" },
      { id: "12.3", label: "Vejamos os valores humanos…", quadrant: "ID" },
      { id: "12.4", label: "Vamos analisar…", quadrant: "SE" },
      { id: "12.5", label: "Vamos ver o quadro geral…", quadrant: "SD" },
      { id: "12.6", label: "Vamos ver o desenvolvimento de equipe…", quadrant: "ID" },
      { id: "12.7", label: "Vamos conhecer o resultado…", quadrant: "SE" },
      { id: "12.8", label: "Este é o grande sucesso conceitual…", quadrant: "SD" },
      { id: "12.9", label: "Vamos manter a lei e a ordem…", quadrant: "IE" },
      { id: "12.10", label: "Vamos inovar e criar sinergia…", quadrant: "SD" },
      { id: "12.11", label: "Vamos participar e envolver…", quadrant: "ID" },
      { id: "12.12", label: "É mais seguro desta forma…", quadrant: "IE" },
    ],
  },
];
